# Example Block Storage Class
# This a general example StorageClass definition for creating volumes with the Hammerspace CSI Plugin
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hs-storage-block-storage
  namespace: kube-system
provisioner: com.hammerspace.csi
volumeBindingMode: WaitForFirstConsumer
parameters:
  # Optional, for use if we are supporting BlockVolumes. Auto-created if it does not exist. Never deleted by the driver
  blockBackingShareName: k8s-block-storage
  # Objectives to set on shares in addition to HS cluster defaults
  objectives: "optimize-for-capacity"
  # The name format of provisioned volumes, %s is replaced with pvc-<uuid>
  volumeNameFormat: "csi-%s"
